services:
  jbtcom-docker:
    container_name: jbtcom-docker
    build: .
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./mycert.crt:/etc/ssl/certs/mycert.crt
      - ./mycert.key:/etc/ssl/private/mycert.key
      - ./src:/var/www/html/
